celebrities = [
    {'name': 'Cristiano Ronaldo', 'follower_count': 815, 'description': 'Footballer', 'country': 'Portugal'},
    {'name': 'Ariana Grande', 'follower_count': 100, 'description': 'Singer and actress', 'country': 'USA'},
    {'name': 'Selena Gomez', 'follower_count': 420, 'description': 'Singer and actress', 'country': 'USA'},
    {'name': 'Khaby Lame', 'follower_count': 160, 'description': 'TikTok content creator', 'country': 'Italy'},
    {'name': 'Camila Coelho', 'follower_count': 104, 'description': 'Fashion influencer', 'country': 'Brazil'},
    {'name': 'Hailey Bieber', 'follower_count': 546, 'description': 'Model and influencer', 'country': 'USA'},
    {'name': 'Charli D’Amelio', 'follower_count': 424, 'description': 'TikTok dancer and influencer', 'country': 'USA'},
    {'name': 'Gigi Hadid', 'follower_count': 212, 'description': 'Model', 'country': 'USA'},
    {'name': 'Kendall Jenner', 'follower_count': 206, 'description': 'Model and reality TV star', 'country': 'USA'},
    {'name': 'Nailea Devora', 'follower_count': 22, 'description': 'Beauty and lifestyle vlogger', 'country': 'USA'},
    {'name': 'Plastique Tiara', 'follower_count': 27, 'description': 'Drag performer and influencer', 'country': 'USA'},
    {'name': 'Stephen King', 'follower_count': 615, 'description': 'Author', 'country': 'USA'},
    {'name': 'Mark Hamill', 'follower_count': 415, 'description': 'Actor', 'country': 'USA'},
    {'name': 'Barbra Streisand', 'follower_count': 142, 'description': 'Singer and actress', 'country': 'USA'},
    {'name': 'Ben Stiller', 'follower_count': 221, 'description': 'Actor and comedian', 'country': 'USA'},
    {'name': 'Gabrielle Union', 'follower_count': 18, 'description': 'Actress', 'country': 'USA'},
    {'name': 'James Gunn', 'follower_count': 135, 'description': 'Director', 'country': 'USA'},
    {'name': 'Jon Cryer', 'follower_count': 38, 'description': 'Actor', 'country': 'USA'},
    {'name': 'Dionne Warwick', 'follower_count': 29, 'description': 'Singer', 'country': 'USA'},
    {'name': 'George Takei', 'follower_count': 32, 'description': 'Actor and activist', 'country': 'USA'},
    {'name': 'Lizzo', 'follower_count': 123, 'description': 'Singer and rapper', 'country': 'USA'},
    {'name': 'Victoria Beckham', 'follower_count': 125, 'description': 'Fashion designer and singer', 'country': 'UK'},
    {'name': 'Olivier Rousteing', 'follower_count': 120, 'description': 'Fashion designer', 'country': 'France'},
    {'name': 'Stella McCartney', 'follower_count': 112, 'description': 'Fashion designer', 'country': 'UK'},
    {'name': 'Karl Lagerfeld', 'follower_count': 111, 'description': 'Fashion designer', 'country': 'Germany'},
    {'name': 'Cara Delevingne', 'follower_count': 99, 'description': 'Model and actress', 'country': 'UK'},
    {'name': 'Gisele Bündchen', 'follower_count': 42, 'description': 'Model', 'country': 'Brazil'},
    {'name': 'Karlie Kloss', 'follower_count': 21, 'description': 'Model', 'country': 'USA'},
    {'name': 'Jourdan Dunn', 'follower_count': 11, 'description': 'Model', 'country': 'UK'},
    {'name': 'Adriana Lima', 'follower_count': 43, 'description': 'Model', 'country': 'Brazil'},
    {'name': 'Naomi Campbell', 'follower_count': 14, 'description': 'Model', 'country': 'UK'},
    {'name': 'Candice Swanepoel', 'follower_count': 50, 'description': 'Model', 'country': 'South Africa'},
    {'name': 'Behati Prinsloo', 'follower_count': 18, 'description': 'Model', 'country': 'Namibia'},
    {'name': 'Kate Upton', 'follower_count': 190, 'description': 'Model and actress', 'country': 'USA'},
    {'name': 'Miranda Kerr', 'follower_count': 55, 'description': 'Model', 'country': 'Australia'},
    {'name': 'Alessandra Ambrosio', 'follower_count': 37, 'description': 'Model', 'country': 'Brazil'},
    {'name': 'Doutzen Kroes', 'follower_count': 27, 'description': 'Model', 'country': 'Netherlands'},
    {'name': 'Tyra Banks', 'follower_count': 26, 'description': 'Model and TV personality', 'country': 'USA'},
    {'name': 'Rosie Huntington-Whiteley', 'follower_count': 29, 'description': 'Model and actress', 'country': 'UK'},
    {'name': 'Barbara Palvin', 'follower_count': 21, 'description': 'Model', 'country': 'Hungary'},
    {'name': 'Lily Aldridge', 'follower_count': 19, 'description': 'Model', 'country': 'USA'},
    {'name': 'Drew Afualo', 'follower_count': 15, 'description': 'Feminist author and influencer', 'country': 'USA'},
    {'name': 'Hannah Neeleman', 'follower_count': 90, 'description': 'Lifestyle content creator', 'country': 'USA'},
    {'name': 'Chris Olsen', 'follower_count': 20, 'description': 'Comedian and content creator', 'country': 'USA'},
    {'name': 'Jake Shane', 'follower_count': 18, 'description': 'Comedian and content creator', 'country': 'USA'},
    {'name': 'Tay Lautner', 'follower_count': 12, 'description': 'Podcaster', 'country': 'USA'},
    {'name': 'Taylor Lautner', 'follower_count': 30, 'description': 'Actor and podcaster', 'country': 'USA'},
    {'name': 'Sean Evans', 'follower_count': 17, 'description': 'Host of Hot Ones', 'country': 'USA'},
    {'name': 'Dasha', 'follower_count': 80, 'description': 'Country singer and dancer', 'country': 'USA'},
    {'name': 'Meredith Hayden', 'follower_count': 110, 'description': 'Culinary expert and influencer', 'country': 'USA'},
    {'name': 'Khaby Lame', 'follower_count': 160, 'description': 'TikTok content creator', 'country': 'Italy'}
]
